import java.time.DayOfWeek
import java.time.LocalTime


data class BossSpawn(
    val day: DayOfWeek,
    val time: LocalTime,
    val bossName: String
)

//BOSS SPAWN TIMETABLE (IT NEVER CHANGES BUT COULD BE BUGGY DURING DST TIME CHANGE FOR A COUPLE OF DAYS [-+1 hour])
val bossSchedule = listOf(
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(0, 15), "Kutum"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(0, 15), "Karanda"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(0, 15), "Uturi"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(2, 0), "Karanda"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(2, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(5, 0), "Kzarka"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(8, 0), "Kzarka"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(12, 0), "Offin"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(16, 0), "Kutum"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(16, 0), "Uturi"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(19, 0), "Nouver"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(19, 0), "Golden Pig King"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(19, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(22, 15), "Kzarka"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(22, 15), "Sangoon"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(22, 15), "Uturi"),
    BossSpawn(DayOfWeek.MONDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(0, 15), "Karanda"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(0, 15), "Golden Pig King"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(2, 0), "Kutum"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(5, 0), "Kzarka"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(8, 0), "Nouver"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(12, 0), "Kutum"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(16, 0), "Nouver"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(16, 0), "Golden Pig King"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(19, 0), "Karanda"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(19, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(19, 0), "Uturi"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(22, 15), "Quint"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(22, 15), "Muraka"),
    BossSpawn(DayOfWeek.TUESDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(0, 15), "Kzarka"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(0, 15), "Kutum"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(0, 15), "Bulgasal"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(2, 0), "Karanda"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(2, 0), "Golden Pig King"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(5, 0), "Kzarka"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(8, 0), "Karanda"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(12, 0), "Nouver"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(16, 0), "Kutum"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(16, 0), "Offin"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(16, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(19, 0), "Vell"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(22, 15), "Kzarka"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(22, 15), "Sangoon"),
    BossSpawn(DayOfWeek.WEDNESDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(0, 15), "Nouver"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(0, 15), "Bulgasal"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(2, 0), "Kutum"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(5, 0), "Nouver"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(8, 0), "Kutum"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(16, 0), "Kzarka"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(16, 0), "Uturi"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(19, 0), "Kutum"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(19, 0), "Sangoon"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(19, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(22, 15), "Quint"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(22, 15), "Muraka"),
    BossSpawn(DayOfWeek.THURSDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(0, 15), "Karanda"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(0, 15), "Sangoon"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(2, 0), "Nouver"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(2, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(5, 0), "Karanda"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(8, 0), "Kutum"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(12, 0), "Karanda"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(16, 0), "Nouver"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(16, 0), "Uturi"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(19, 0), "Kzarka"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(19, 0), "Golden Pig King"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(22, 15), "Kzarka"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(22, 15), "Kutum"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(22, 15), "Bulgasal"),
    BossSpawn(DayOfWeek.FRIDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(0, 15), "Karanda"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(0, 15), "Golden Pig King"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(0, 15), "Sangoon"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(2, 0), "Offin"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(2, 0), "Golden Pig King"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(2, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(5, 0), "Nouver"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(8, 0), "Kutum"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(12, 0), "Nouver"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(16, 0), "Black Shadow"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(19, 0), "Karanda"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(19, 0), "Kzarka"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(19, 0), "Bulgasal"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(19, 0), "Sangoon"),
    BossSpawn(DayOfWeek.SATURDAY, LocalTime.of(23, 15), "Garmoth"),

    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(0, 15), "Nouver"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(0, 15), "Kutum"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(0, 15), "Golden Pig King"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(0, 15), "Uturi"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(2, 0), "Kzarka"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(2, 0), "Sangoon"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(5, 0), "Kutum"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(8, 0), "Nouver"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(12, 0), "Kzarka"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(14, 0), "Garmoth"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(16, 0), "Vell"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(19, 15), "Garmoth"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(22, 15), "Kzarka"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(22, 15), "Nouver"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(22, 15), "Golden Pig King"),
    BossSpawn(DayOfWeek.SUNDAY, LocalTime.of(22, 15), "Sangoon")
)